server:
  port: 4001

spring:
  application:
    name: cloud-rabbitmq-producer
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#  nacos注册中心
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'

#eureka注册中心
#eureka:
#  client:
#    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka