server:
  port: 8004

spring:
  application:
    name: cloud-provider-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:ORCL
    username: MYJAVA
    password: 1234
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name} #对外暴露的服务名称

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.anzaiyun.entity
