server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:ORCL
    username: MYJAVA
    password: 1234

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.anzaiyun.entity