server:
  port: 8010

spring:
  application:
    name: cloud-provider-hystrix-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:ORCL
    username: MYJAVA
    password: 1234

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.anzaiyun.entity

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: cloud-provider-hystrix-payment
    prefer-ip-address: true    #访问路径可以显示IP地址